name: CICD for PR to staging with yaml to GIT

on:
  pull_request:
    branches: [ staging ]

jobs:
  
  build:
    if: github.repository_owner == 'raul3520'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login

      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
    
    - name: Kubernetes set context
      uses: Azure/k8s-set-context@v1.1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG}}
    
    
    - name: Build the Docker image
      run: |

        tag="$(date '+%Y-%m')-${GITHUB_SHA::8}"
        echo $tag
        #docker build . --tag raul3520/mynewtest:$tag
        #docker push raul3520/mynewtest:$tag
        


    - name: Push yaml to github repo    
      run: |
        sed -i "s/TAG/$tag/g" k8s.yaml
        cat k8s.yaml
        #kubectl apply -f k8s.yaml
        #sleep 18
        #sh k8monit.sh
        git config --global user.email "raul3520@gmail.com"
        git config --global user.name "raul3520"
        git remote set-url origin https://raul3520:${{ secrets.PAT}}@github.com/raul3520/yamlcode.git
        git add k8s.yaml
        git commit -m "test"
        git push origin main
        

        




